apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-deals
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-production-http01
spec:
  ingressClassName: nginx
  rules:
    - host: game-deals.k8s.funkyboy.zone
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-django
                port:
                  name: http

  tls:
    - hosts:
        - game-deals.k8s.funkyboy.zone
      secretName: game-deals-k8s-funkyboy-zone-ingress-cert
