apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
  # Disable for now, eventually will undeploy once fully decommissioned
  - name: discord-azure-boot
    count: 0

commonLabels:
  component: bot

configMapGenerator:
  - name: discord-azure-boot-config
    files:
      - ./conf/config.json5

resources:
  - ./resources/deployment.yaml
