apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-deals

resources:
  - resources/namespace.yaml
  - https://github.com/WWPOL/Game-Deals.git//deployment/base?ref=django
  - resources/ingress.yaml

images:
- name: ghcr.io/wwpol/game-deals
  newTag: django-0f09e00

secretGenerator:
- name: postgres-secret
  envs:
  - conf/postgres.env
- name: django-secret
  envs:
  - conf/django.env

patches:
- path: patches/app-django.yaml
- path: patches/app-celery.yaml
