apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    project: media-server
    component: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: sonarr
  template:
    metadata:
      labels:
        project: media-server
        component: sonarr
    spec:
      priorityClassName: streaming
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: project
                    operator: In
                    values:
                      - media-server
                  - key: component
                    operator: In
                    values:
                      - emby
              topologyKey: kubernetes.io/hostname
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.10
          ports:
            - name: http
              containerPort: 8989
          
          volumeMounts:
            - name: config-do-block
              mountPath: /config
            - name: media-do-block
              mountPath: /media
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: config-do-block
          persistentVolumeClaim:
            claimName: sonarr-config-do-block
        - name: media-do-block
          persistentVolumeClaim:
            claimName: media-files-do-block
