apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    project: media-server
    component: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: radarr
  template:
    metadata:
      labels:
        project: media-server
        component: radarr
    spec:
      priorityClassName: streaming
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: project
                    operator: In
                    values:
                      - media-server
                  - key: component
                    operator: In
                    values:
                      - emby
              topologyKey: kubernetes.io/hostname
      containers:
        - name: radarr
          image: linuxserver/radarr:5.14.0
          ports:
            - name: http
              containerPort: 7878
          
          volumeMounts:
            - name: config-do-block
              mountPath: /config
            - name: media-do-block
              mountPath: /media
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: config-do-block
          persistentVolumeClaim:
            claimName: radarr-config-do-block
        - name: media-do-block
          persistentVolumeClaim:
            claimName: media-files-do-block
