components:
  # Base Cluster Functionality
  - path: ./base/priority-classes
  - path: ./base/nginx-ingress
  - path: ./base/operator-lifecycle-manager
  - path: ./base/cert-manager

  # Cluster Adminstrative Tools
  - path: ./base/kubernetes-dashboard
  - path: ./base/wireguard/
  - path: ./base/headscale/headscale-operator
  - path: ./base/headscale/headscale-instance
  - path: ./base/headscale/web-ui
  - path: ./base/coredns/
  - path: ./base/monitoring/
  # - path: ./base/monitoring/resources/kube-prometheus/crds
  #   strategy: big-diff
  # - path: ./base/monitoring/resources/kube-prometheus/core/
  # - path: ./base/iperf/

  # End User Services
  - path: ./base/media-server/
  - path: ./base/discord-azure-boot/ # No longer needed, all game servers are self hosted now
  - path: ./base/noahhuppert-com/
  - path: ./base/noahhuppert-com-beta/
  - path: ./base/funkyboy-zone/
  - path: ./base/goldblum-zone/
  - path: ./base/ham-radio-questions/
  # WIP: - path: ./base/netbox/
  - path: ./base/factorio/
  - path: ./base/infoline-dashboard/
  #- path: ./base/syncthing
