apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale

resources:
  - resources/headscale-instance.yaml
  - resources/ingress.yaml
  - resources/noah-pascal-user.yaml
  - resources/noah-s23-user.yaml
