apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale-webui
  labels:
    component: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      project: headscale
      component: webui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: headscale
        component: webui
    spec:
      containers:
        - name: webui
          image: ghcr.io/gurucomputing/headscale-ui:2025.08.23
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
