apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    project: media-server
    component: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: jellyseerr
  template:
    metadata:
      labels:
        project: media-server
        component: jellyseerr
    spec:
      priorityClassName: streaming
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:2.1.0
          ports:
            - name: http
              containerPort: 5055
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr-config-do-block
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: jellyseerr-config-do-block
          persistentVolumeClaim:
            claimName: jellyseerr-config-do-block
